nueva entera I 1
nueva logica L 1
nueva cadena C prueba
nueva pruebaLogica L 1
vaya Itere
etiqueta iterar 8
nueva flotante2 R 2.2
cargue entera
sume flotante2
NO logica pruebaLogica
multiplique flotante2
nueva cero I 0
etiqueta pruebaEtiqueta 7
etiqueta Itere 2
cargue cero
divida entera
sume cero
reste flotante2
potencia entera
Y logica logica pruebaLogica
vayasi Itere pruebaEtiqueta
vaya iterar
cargue flotante2
almacene pruebaLogica
multiplique cero
retorne 0
