// Programa para calcular el factorial de 5
nueva unidad I 1
nueva m I 5
nueva respuesta I 1
nueva intermedia I 0
cargue m
almacene respuesta
reste unidad
// Se inicia el ciclo de cálculo del factorial
almacene intermedia
cargue respuesta
multiplique intermedia
almacene respuesta
cargue intermedia
reste unidad
vayasi itere fin
etiqueta itere 8
etiqueta fin 19
muestre respuesta
imprima respuesta
retorne
//PRUEBA DE EDICIÓN