// Calcula el producto de dos valores entrados por teclado.
nueva unidad I 1
nueva m I 0
nueva n I 0
lea m
lea n
nueva respuesta I 0
nueva resultado C Resultado=
nueva intermedia I 0
cargue n
// inicia ciclo
reste unidad
almacene intermedia
cargue respuesta
sume m
almacene respuesta
cargue intermedia
vayasi ciclo fin
etiqueta ciclo 10
etiqueta fin 23
muestre resultado
muestre respuesta
imprima resultado
imprima respuesta
retorne 0