// Programa para calcular el factorial de 5
nueva unidad2 I 1
nueva m2 I 5
nueva respuesta I 1
nueva intermedia I 0
cargue m2
almacene respuesta
reste unidad2
// Se inicia el ciclo de cálculo del factorial
almacene intermedia
cargue respuesta
multiplique intermedia
almacene respuesta
cargue intermedia
reste unidad2
vayasi itere fin
etiqueta itere 8
etiqueta fin 19
muestre respuesta
imprima respuesta
retorne
//PRUEBA DE EDICIÓN