// Calcula el producto de dos valores entrados por teclado.
nueva unidad3 I 1
nueva m3 I 0
nueva n3 I 0
lea m3
lea n3
nueva respuesta I 0
nueva resultado C Resultado=
nueva intermedia I 0
cargue n3
// inicia ciclo
reste unidad3
almacene intermedia
cargue respuesta
sume m3
almacene respuesta
cargue intermedia
vayasi ciclo fin
etiqueta ciclo 10
etiqueta fin 23
muestre resultado
muestre respuesta
imprima resultado
imprima respuesta
retorne 0